services:
  # A web service on the Ruby native runtime
  - type: web
    runtime: node
    name: ESGI-nodeapp
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ESGI-db
          property: connectionString


databases:
  - name: ESGI-db
    region: frankfurt
    plan: free
